[supabase]
url = "https://zilucwwoqofdxktqmewj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppbHVjd3dvcW9mZHhrdHFtZXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDUyMzIsImV4cCI6MjA3MjQ4MTIzMn0.xVBOb7UFkJX8q3_HMj9_iucS5PJIcnG-UZW3E_9gul0"